Added a check for GCJ, and a note telling the user to get normal Java.

diff --git a/resources/os-specific/unix/jin b/resources/os-specific/unix/jin
--- a/resources/os-specific/unix/jin
+++ b/resources/os-specific/unix/jin
@@ -1,14 +1,31 @@
 #!/bin/sh
 
+# Java command
+JAVA_CMD=java
+
+# Check if GCJ
+readlink -f $JAVA_CMD | grep -i -q "gij\|gcj"
+if [ $? -eq 0 ]
+then
+	$JAVA_CMD -version 2>&1 | grep -i -q "gcj\|gnu\|gij"
+	if [ $? -eq 0 ]
+	then
+		echo "You seem to be running GNU's Java implementation, which is"
+		echo "incomplete. To run Jin, standard Java is required. You can obtain"
+		echo "it at http://www.java.com"
+		exit
+	fi
+fi
+
 # Follow links
 filename=`readlink -f $0`
 if [ -z "$filename" ]
 then
-  filename=$0
+	filename=$0
 fi
 
 # Change to Jin's directory - Jin needs to be run from its directory
 cd `dirname $filename`
 
 # Run Jin
-java $JAVA_OPTS -jar jin.jar $*
+$JAVA_CMD $JAVA_OPTS -jar jin.jar $*
